name: vania_furniture_api
description: Sample Vania backend web application framework
version: 1.0.0

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  decimal: ^3.0.2
  stripe: ^4.11.0
  vania: ^0.3.1


dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0

dependency_overrides:
  pointycastle: 3.7.3